-- Create a schema "videohoster" in database "postgres"
CREATE SCHEMA IF NOT EXISTS videohoster;

DROP TABLE IF EXISTS videohoster.USERS CASCADE;

CREATE TABLE IF NOT EXISTS videohoster.USERS(
	ID SERIAL PRIMARY KEY,
    UUID VARCHAR(36) NOT NULL,
    ROLE VARCHAR(36),
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    SALT VARCHAR(200) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    MOBILE_PHONE VARCHAR(50) NOT NULL,
    LAST_LOGIN_AT TIMESTAMP NULL
);

ALTER TABLE videohoster.USERS ADD CONSTRAINT UK_USERS_EMAIL UNIQUE(EMAIL);