DROP TABLE IF EXISTS videohoster.VIDEOS CASCADE;

CREATE TABLE IF NOT EXISTS videohoster.VIDEOS(
	ID SERIAL PRIMARY KEY,
    UUID VARCHAR(36) NOT NULL,
    VIDEO VARCHAR(100),
    NAME VARCHAR(200),
    DESCRIPTION VARCHAR (200),
    NO_OF_LIKES INTEGER ,
    USER_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP,
    STATUS VARCHAR(26)
);

ALTER TABLE videohoster.VIDEOS ADD CONSTRAINT FK_VIDEOS FOREIGN KEY(USER_ID) REFERENCES videohoster.USERS(ID);
